export type Message = { type: 'input' | 'output' | 'error'; text: string };

export type Session = {
    id: string;
    history: Message[];
    input: string;
    isExecuting: boolean;
    historyIndex: number;
    pendingCmd: string | null;
};

export const TAB_COMPLETIONS = [
    'quote --symbol ', 'historical --symbol ', 'profile --symbol ',
    'search --query ', 'news', 'income --symbol ', 'balance --symbol ',
    'calendar', 'cpi', 'gdp', 'treasury', 'options --symbol ',
    'equity price historical --symbol ', 'equity price performance --symbol ',
    'equity historical_market_cap --symbol ',
    'crypto price historical --symbol BTC-USD --chart true',
    'crypto price historical --symbol ETH-USD --chart true',
    'crypto price historical --symbol ',
    'currency price historical --symbol EURUSD=X --chart true',
    'currency price historical --symbol ',
    'etf historical --symbol SPY --chart true',
    'etf historical --symbol ', 'etf holdings --symbol ', 'etf price_performance --symbol ',
    'derivatives futures curve --symbol CL --chart true',
    'derivatives futures historical --symbol ',
    'derivatives options surface --symbol SPY --chart true',
    'fixedincome government yield_curve --chart true',
    'fixedincome government yield_curve --date ',
    'index price historical --symbol ^GSPC --chart true',
    'index price historical --symbol ^NDX --chart true',
    'index price historical --symbol ',
    'economy fred_series --symbol GDP --chart true',
    'economy fred_series --symbol CPIAUCSL --chart true',
    'economy fred_series --symbol FEDFUNDS --chart true',
    'economy fred_series --symbol ',
    'economy shipping chokepoint_info --chart true',
    'economy shipping port_info --chart true',
    'economy survey bls_series --symbol ',
    'technical macd --symbol ', 'technical rsi --symbol ',
    'technical ema --symbol ', 'technical sma --symbol ',
    'technical wma --symbol ', 'technical hma --symbol ', 'technical zlma --symbol ',
    'technical adx --symbol ', 'technical aroon --symbol ',
    'technical cones --symbol ',
    'technical relative_rotation --symbol ',
    // Factor / Sector Analytics — Plotly charts
    'analytics factor --tickers ',
    'analytics factor --tickers AAPL,MSFT,NVDA,TSLA,META',
    'analytics factor --tickers AAPL,MSFT,NVDA --benchmark SPY --days 252',
    'analytics sector --tickers ',
    'analytics sector --tickers AAPL,MSFT,NVDA,JPM,JNJ,XOM',
    'help', 'clear',
];

export const getTerminalTheme = (isDark: boolean) => (isDark ? {
    bg: 'bg-[#050505]/60',
    bgSolid: 'bg-black/95',
    bgTab: 'bg-zinc-900/20',
    bgTabActive: 'bg-cyan-500/10',
    border: 'border-white/5',
    borderTab: 'border-cyan-500/10',
    text: 'text-zinc-400',
    textBright: 'text-white',
    textDim: 'text-zinc-500',
    textInput: 'text-cyan-400 drop-shadow-[0_0_8px_rgba(34,211,238,0.4)]',
    textCmd: 'text-cyan-400 font-bold',
    textError: 'text-rose-400 font-bold drop-shadow-[0_0_8px_rgba(244,63,94,0.4)]',
    textOutput: 'text-zinc-300',
    gutter: 'text-zinc-600/40',
    gutterActive: 'text-cyan-400 bg-cyan-500/5 shadow-[inset_-2px_0_0_0_rgba(34,211,238,0.4)]',
    gutterBg: 'bg-black/10',
    modeNormal: 'bg-zinc-800 text-zinc-400 border border-white/5',
    modeInsert: 'bg-cyan-600 text-white font-bold shadow-[0_0_15px_rgba(34,211,238,0.3)]',
    statusBg: 'bg-black/40 border-t border-white/5',
    statusBg2: 'bg-cyan-500/10 text-cyan-400',
    statusBg3: 'bg-black/20',
    cursor: 'bg-cyan-400',
    cursorBorder: 'border-cyan-400',
    accentGlow: 'shadow-[0_0_20px_rgba(34,211,238,0.2)]',
    warn: 'text-amber-400 drop-shadow-[0_0_8px_rgba(251,191,36,0.6)]',
    warnDot: 'bg-amber-400 shadow-[0_0_12px_rgba(251,191,36,0.8)]',
    panelBlur: 'backdrop-blur-2xl transition-all duration-700',
    tabIndicator: 'bg-cyan-500',
} : {
    bg: 'bg-white/40',
    bgSolid: 'bg-[#ffffff]/90',
    bgTab: 'bg-slate-200/20',
    bgTabActive: 'bg-teal-500/10',
    border: 'border-black/5',
    borderTab: 'border-teal-500/10',
    text: 'text-slate-600',
    textBright: 'text-black',
    textDim: 'text-slate-400',
    textInput: 'text-teal-600 font-bold',
    textCmd: 'text-teal-600 font-bold',
    textError: 'text-red-500 font-bold',
    textOutput: 'text-slate-800',
    gutter: 'text-slate-300',
    gutterActive: 'text-teal-600 font-bold border-r-2 border-teal-500/50',
    gutterBg: 'bg-slate-100/10',
    modeNormal: 'bg-slate-200 text-slate-600 border border-black/5',
    modeInsert: 'bg-teal-500 text-white shadow-sm',
    statusBg: 'bg-white/40 border-t border-black/5',
    statusBg2: 'bg-teal-500/10 text-teal-700',
    statusBg3: 'bg-slate-100/30',
    cursor: 'bg-teal-600',
    cursorBorder: 'border-teal-600',
    accentGlow: 'shadow-[0_0_15px_rgba(20,184,166,0.2)]',
    warn: 'text-amber-600',
    warnDot: 'bg-amber-500',
    panelBlur: 'backdrop-blur-2xl transition-all duration-700',
    tabIndicator: 'bg-teal-500',
});
