export type Message = { type: 'input' | 'output' | 'error'; text: string };

export type Session = {
    id: string;
    history: Message[];
    input: string;
    isExecuting: boolean;
    historyIndex: number;
    pendingCmd: string | null;
};

export const TAB_COMPLETIONS = [
    'quote --symbol ', 'historical --symbol ', 'profile --symbol ',
    'search --query ', 'news', 'income --symbol ', 'balance --symbol ',
    'calendar', 'cpi', 'gdp', 'treasury', 'options --symbol ',
    'equity price historical --symbol ', 'equity price performance --symbol ',
    'equity historical_market_cap --symbol ',
    'crypto price historical --symbol BTC-USD --chart true',
    'crypto price historical --symbol ETH-USD --chart true',
    'crypto price historical --symbol ',
    'currency price historical --symbol EURUSD=X --chart true',
    'currency price historical --symbol ',
    'etf historical --symbol SPY --chart true',
    'etf historical --symbol ', 'etf holdings --symbol ', 'etf price_performance --symbol ',
    'derivatives futures curve --symbol CL --chart true',
    'derivatives futures historical --symbol ',
    'derivatives options surface --symbol SPY --chart true',
    'fixedincome government yield_curve --chart true',
    'fixedincome government yield_curve --date ',
    'index price historical --symbol ^GSPC --chart true',
    'index price historical --symbol ^NDX --chart true',
    'index price historical --symbol ',
    'economy fred_series --symbol GDP --chart true',
    'economy fred_series --symbol CPIAUCSL --chart true',
    'economy fred_series --symbol FEDFUNDS --chart true',
    'economy fred_series --symbol ',
    'economy shipping chokepoint_info --chart true',
    'economy shipping port_info --chart true',
    'economy survey bls_series --symbol ',
    'technical macd --symbol ', 'technical rsi --symbol ',
    'technical ema --symbol ', 'technical sma --symbol ',
    'technical wma --symbol ', 'technical hma --symbol ', 'technical zlma --symbol ',
    'technical adx --symbol ', 'technical aroon --symbol ',
    'technical cones --symbol ',
    'technical relative_rotation --symbol ',
    'help', 'clear',
];

export const getTerminalTheme = (isDark: boolean) => (isDark ? {
    bg: 'bg-zinc-950/80',
    bgSolid: 'bg-black/90',
    bgTab: 'bg-zinc-900/60',
    bgTabActive: 'bg-cyan-950/30',
    border: 'border-cyan-500/30',
    borderTab: 'border-cyan-900/40',
    text: 'text-zinc-100',
    textBright: 'text-white',
    textDim: 'text-cyan-500/60',
    textInput: 'text-cyan-300 drop-shadow-[0_0_5px_rgba(103,232,249,0.4)]',
    textCmd: 'text-cyan-400 font-bold',
    textError: 'text-rose-400 font-bold drop-shadow-[0_0_8px_rgba(244,63,94,0.4)]',
    textOutput: 'text-zinc-200',
    gutter: 'text-cyan-900/70',
    gutterActive: 'text-cyan-400 bg-cyan-950/20 shadow-[inset_-2px_0_0_0_rgba(34,211,238,0.5)]',
    gutterBg: 'bg-zinc-950/40',
    modeNormal: 'bg-cyan-600 text-white font-bold',
    modeInsert: 'bg-teal-400 text-black font-bold shadow-[0_0_15px_rgba(45,212,191,0.5)]',
    statusBg: 'bg-zinc-900/90 border-t border-cyan-900/30',
    statusBg2: 'bg-cyan-950/80 text-cyan-200',
    statusBg3: 'bg-black/90',
    cursor: 'bg-cyan-400',
    cursorBorder: 'border-cyan-400',
    accentGlow: 'shadow-[0_0_15px_rgba(34,211,238,0.6)]',
    warn: 'text-amber-400 drop-shadow-[0_0_8px_rgba(251,191,36,0.6)]',
    warnDot: 'bg-amber-400 shadow-[0_0_12px_rgba(251,191,36,0.8)]',
    panelBlur: 'backdrop-blur-3xl',
    tabIndicator: 'bg-cyan-400',
} : {
    bg: 'bg-[#eff1f5]/80',
    bgSolid: 'bg-[#e6e9ef]/90',
    bgTab: 'bg-[#e6e9ef]/60',
    bgTabActive: 'bg-teal-50/80',
    border: 'border-teal-500/30',
    borderTab: 'border-[#ccd0da]/60',
    text: 'text-slate-800',
    textBright: 'text-black',
    textDim: 'text-slate-500',
    textInput: 'text-teal-700 font-bold',
    textCmd: 'text-teal-600 font-bold',
    textError: 'text-red-600 font-bold',
    textOutput: 'text-slate-800',
    gutter: 'text-slate-400',
    gutterActive: 'text-teal-600 font-bold border-r-2 border-teal-500',
    gutterBg: 'bg-slate-100/50',
    modeNormal: 'bg-teal-600 text-white',
    modeInsert: 'bg-emerald-500 text-white shadow-sm',
    statusBg: 'bg-slate-200/90',
    statusBg2: 'bg-slate-300',
    statusBg3: 'bg-slate-100/90',
    cursor: 'bg-teal-600',
    cursorBorder: 'border-teal-600',
    accentGlow: 'shadow-[0_0_12px_rgba(20,184,166,0.3)]',
    warn: 'text-[#df8e1d]',
    warnDot: 'bg-[#df8e1d]',
    panelBlur: 'backdrop-blur-3xl',
    tabIndicator: 'bg-teal-500',
});
